name: "Teste de Action"
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    teste-action-job:
        permissions:
            issues: write
            pull-requests: write 
        runs-on: ubuntu-latest
        name: Execução de Custom Action (Docker)
        steps:
            - name: Adicionando Comentário
              id: comment_step
              uses: leosimao88/action-docker@v1.0.0
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário docker"
                GITHUB_REPOSITORY: ${{ github.repository }}
            - name: "Mostrar o ID do comentário"
              run: |
                echo 'ID do comentário é: ${{ steps.comment_step.outputs.comment-id }}'
