name: "Teste de Action"
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    teste-action-job:
        runs-on: ubuntu-latest
        name: Execução de Custom Action
        steps:
            - name: Adicionando Comentário
              uses: leosimao88/action-js@main
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário"